//! The known-adapter table.
//!
//! Generated from fastp 1.3.6 `src/knownadapters.h` (MIT, (c) 2016 OpenGene),
//! which draws on github.com/stephenturner/adapters. Each entry keeps the
//! first human-readable name from fastp's `|`-separated alias list.
//!
//! fastp iterates a `std::map<string,string>`, so it visits adapters in
//! lexicographic order by sequence; ties in `check_known_adapters` resolve to
//! whichever it saw first. We sort the table the same way at load so the tie
//! break matches.

/// (sequence, name), in fastp's `std::map` iteration order.
pub static KNOWN_ADAPTERS: &[(&[u8], &str)] = &[
    (b"AACTGTAGGCACCATCAAT", "QIASeq miRNA adapter"),
    (b"AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA", "MGI/BGI adapter (forward)"),
    (b"AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG", "MGI/BGI adapter (reverse)"),
    (b"AATGATACGGCGACCACCGACAGGTTCAGAGTTCTACAGTCCGA", "Illumina DpnII expression PCR Primer 2"),
    (b"AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA", "Illumina RNA PCR Primer"),
    (b"AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT", "TruSeq_Universal_Adapter"),
    (b"AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCTAGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG", "pcr_dimer"),
    (b"AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCTCAAGCAGAAGACGGCATACGAGCTCTTCCGATCT", "PCR_Primers"),
    (b"ACACTCTTTCCCTACACGACGCTCTTCCGATCT", "Illumina Single End Sequencing Primer"),
(b"AGATCGGAAGAGCACACGTCTGAACTCCAGTCA", "Illumina TruSeq Adapter Read 1"),
    (b"AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC", "PE2_rc"),
    (b"AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG", "Reverse_adapter"),
    (b"AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAG", "TruSeq2_PE_r"),
    (b"AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG", "PCR_Primer2_rc"),
    (b"AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTGAAA", "PhiX_read1_adapter"),
    (b"AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT", "Illumina TruSeq Adapter Read 2"),
    (b"AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA", "PE1_rc"),
    (b"AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT", "PCR_Primer1_rc"),
    (b"AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATTAAAAAA", "PhiX_read2_adapter"),
    (b"AGATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG", "TruSeq2_SE"),
    (b"CAAGCAGAAGACGGCATACGAGATAAAATGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 35"),
    (b"CAAGCAGAAGACGGCATACGAGATAAGCTAGTGACTGGAGTTC", "Illumina PCR Primer Index 10"),
    (b"CAAGCAGAAGACGGCATACGAGATAAGCTAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 10"),
    (b"CAAGCAGAAGACGGCATACGAGATACATCGGTGACTGGAGTTC", "Illumina PCR Primer Index 2"),
    (b"CAAGCAGAAGACGGCATACGAGATACATCGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 2"),
    (b"CAAGCAGAAGACGGCATACGAGATAGCTAGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 38"),
    (b"CAAGCAGAAGACGGCATACGAGATAGGAATGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 27"),
    (b"CAAGCAGAAGACGGCATACGAGATATCAGTGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 25"),
    (b"CAAGCAGAAGACGGCATACGAGATATCGTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 31"),
    (b"CAAGCAGAAGACGGCATACGAGATATTATAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 44"),
    (b"CAAGCAGAAGACGGCATACGAGATATTCCGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 37"),
    (b"CAAGCAGAAGACGGCATACGAGATATTGGCGTGACTGGAGTTC", "Illumina PCR Primer Index 6"),
    (b"CAAGCAGAAGACGGCATACGAGATATTGGCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 6"),
    (b"CAAGCAGAAGACGGCATACGAGATCACTGTGTGACTGGAGTTC", "Illumina PCR Primer Index 5"),
    (b"CAAGCAGAAGACGGCATACGAGATCACTGTGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 5"),
    (b"CAAGCAGAAGACGGCATACGAGATCCACTCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 23"),
    (b"CAAGCAGAAGACGGCATACGAGATCCGGTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 30"),
    (b"CAAGCAGAAGACGGCATACGAGATCGAAACGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 21"),
    (b"CAAGCAGAAGACGGCATACGAGATCGATTAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 42"),
    (b"CAAGCAGAAGACGGCATACGAGATCGCCTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 33"),
    (b"CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT", "PrefixPE/2"),
    (b"CAAGCAGAAGACGGCATACGAGATCGTACGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 22"),
    (b"CAAGCAGAAGACGGCATACGAGATCGTGATGTGACTGGAGTTC", "Illumina PCR Primer Index 1"),
    (b"CAAGCAGAAGACGGCATACGAGATCGTGATGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 1"),
    (b"CAAGCAGAAGACGGCATACGAGATCTCTACGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 17"),
    (b"CAAGCAGAAGACGGCATACGAGATCTGATCGTGACTGGAGTTC", "Illumina PCR Primer Index 9"),
    (b"CAAGCAGAAGACGGCATACGAGATCTGATCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 9"),
    (b"CAAGCAGAAGACGGCATACGAGATCTTCGAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 47"),
    (b"CAAGCAGAAGACGGCATACGAGATCTTTTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 28"),
    (b"CAAGCAGAAGACGGCATACGAGATGAATGAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 45"),
    (b"CAAGCAGAAGACGGCATACGAGATGATCTGGTGACTGGAGTTC", "Illumina PCR Primer Index 7"),
    (b"CAAGCAGAAGACGGCATACGAGATGATCTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 7"),
    (b"CAAGCAGAAGACGGCATACGAGATGCCATGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 34"),
    (b"CAAGCAGAAGACGGCATACGAGATGCCTAAGTGACTGGAGTTC", "Illumina PCR Primer Index 3"),
    (b"CAAGCAGAAGACGGCATACGAGATGCCTAAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 3"),
    (b"CAAGCAGAAGACGGCATACGAGATGCGGACGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 18"),
    (b"CAAGCAGAAGACGGCATACGAGATGCTACCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 24"),
    (b"CAAGCAGAAGACGGCATACGAGATGCTCATGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 26"),
    (b"CAAGCAGAAGACGGCATACGAGATGCTGTAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 43"),
    (b"CAAGCAGAAGACGGCATACGAGATGGAACTGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 14"),
    (b"CAAGCAGAAGACGGCATACGAGATGGACGGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 16"),
    (b"CAAGCAGAAGACGGCATACGAGATGGCCACGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 20"),
    (b"CAAGCAGAAGACGGCATACGAGATGTAGCCGTGACTGGAGTTC", "Illumina PCR Primer Index 11"),
    (b"CAAGCAGAAGACGGCATACGAGATGTAGCCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 11"),
    (b"CAAGCAGAAGACGGCATACGAGATGTATAGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 39"),
    (b"CAAGCAGAAGACGGCATACGAGATGTCGTCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 41"),
    (b"CAAGCAGAAGACGGCATACGAGATTACAAGGTGACTGGAGTTC", "Illumina PCR Primer Index 12"),
    (b"CAAGCAGAAGACGGCATACGAGATTACAAGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 12"),
    (b"CAAGCAGAAGACGGCATACGAGATTAGTTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 29"),
    (b"CAAGCAGAAGACGGCATACGAGATTCAAGTGTGACTGGAGTTC", "Illumina PCR Primer Index 8"),
    (b"CAAGCAGAAGACGGCATACGAGATTCAAGTGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 8"),
    (b"CAAGCAGAAGACGGCATACGAGATTCGGGAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 46"),
    (b"CAAGCAGAAGACGGCATACGAGATTCTGAGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 40"),
    (b"CAAGCAGAAGACGGCATACGAGATTGACATGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 15"),
    (b"CAAGCAGAAGACGGCATACGAGATTGAGTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 32"),
    (b"CAAGCAGAAGACGGCATACGAGATTGCCGAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 48"),
    (b"CAAGCAGAAGACGGCATACGAGATTGGTCAGTGACTGGAGTTC", "Illumina PCR Primer Index 4"),
    (b"CAAGCAGAAGACGGCATACGAGATTGGTCAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 4"),
    (b"CAAGCAGAAGACGGCATACGAGATTGTTGGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 36"),
    (b"CAAGCAGAAGACGGCATACGAGATTTGACTGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 13"),
    (b"CAAGCAGAAGACGGCATACGAGATTTTCACGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", "RNA PCR Primer, Index 19"),
    (b"CAAGCAGAAGACGGCATACGAGCTCTTCCGATCT", "Illumina Single End Adapter 2"),
    (b"CCACTACGCCTCCGCTTTCCTCTCTATGGGCAGTCGGTGAT", "ABI Solid3 Adapter B"),
    (b"CCGACAGGTTCAGAGTTCTACAGTCCGACATG", "Illumina NlaIII expression Sequencing Primer"),
    (b"CCGAGCCCACGAGACAAGAGGCAATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N711"),
    (b"CCGAGCCCACGAGACACTCGCTAATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N716"),
    (b"CCGAGCCCACGAGACACTGAGCGATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N724"),
    (b"CCGAGCCCACGAGACAGGCAGAAATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N703"),
    (b"CCGAGCCCACGAGACATCTCAGGATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N715"),
    (b"CCGAGCCCACGAGACATGCGCAGATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N722"),
    (b"CCGAGCCCACGAGACCAGAGAGGATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N708"),
    (b"CCGAGCCCACGAGACCCTAAGACATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N726"),
    (b"CCGAGCCCACGAGACCGAGGCTGATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N710"),
    (b"CCGAGCCCACGAGACCGATCAGTATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N727"),
    (b"CCGAGCCCACGAGACCGGAGCCTATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N720"),
    (b"CCGAGCCCACGAGACCGTACTAGATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N702"),
    (b"CCGAGCCCACGAGACCTCTCTACATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N707"),
    (b"CCGAGCCCACGAGACGCGTAGTAATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N719"),
    (b"CCGAGCCCACGAGACGCTACGCTATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N709"),
    (b"CCGAGCCCACGAGACGCTCATGAATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N714"),
    (b"CCGAGCCCACGAGACGGACTCCTATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N705"),
    (b"CCGAGCCCACGAGACGGAGCTACATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N718"),
    (b"CCGAGCCCACGAGACGTAGAGGAATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N712"),
    (b"CCGAGCCCACGAGACTAAGGCGAATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N701"),
    (b"CCGAGCCCACGAGACTACGCTGCATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N721"),
    (b"CCGAGCCCACGAGACTAGCGCTCATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N723"),
    (b"CCGAGCCCACGAGACTAGGCATGATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N706"),
    (b"CCGAGCCCACGAGACTCCTGAGCATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_and_Nextera_Enrichment_N704"),
    (b"CCGAGCCCACGAGACTCGACGTCATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N729"),
    (b"CCGAGCCCACGAGACTGCAGCTAATCTCGTATGCCGTCTTCTGCTTG", "I7_Primer_Nextera_XT_Index_Kit_v2_N728"),
    (b"CGACAGGTTCAGAGTTCTACAGTCCGACGATC", "Illumina DpnII expression Sequencing Primer"),
    (b"CGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT", "Illumina Paired End Sequencing Primer 2"),
    (b"CTAATACGACTCACTATAGGGCAAGCAGTGGTATCAACGCAGAGT", "Clontech Universal Primer Mix Long"),
    (b"CTGAGCGGGCTGGCAAGGCAGACCGATCTCGTATGCCGTCTTCTGCTTG", "I7_Adapter_Nextera_No_Barcode"),
    (b"CTGATGGCGCGAGGGAGGCGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Adapter_Nextera"),
    (b"CTGCCCCGGGTTCCTCATTCTCTCAGCAGCATG", "ABI Solid3 Adapter A"),
    (b"CTGTCTCTTATACACATCTCCGAGCCCACGAGAC", "I7_Nextera_Transposase_1"),
    (b"CTGTCTCTTATACACATCTCTGAGCGGGCTGGCAAGGC", "I7_Nextera_Transposase_2"),
    (b"CTGTCTCTTATACACATCTCTGATGGCGCGAGGGAGGC", "I5_Nextera_Transposase_2"),
    (b"CTGTCTCTTATACACATCTGACGCTGCCGACGA", "I5_Nextera_Transposase_1"),
    (b"GACGCTGCCGACGAACTCTAGGGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_Index_Kit_v2_S516"),
    (b"GACGCTGCCGACGAAGAGGATAGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]503"),
    (b"GACGCTGCCGACGAAGCTAGAAGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_Index_Kit_v2_S515"),
    (b"GACGCTGCCGACGAAGGCTTAGGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]508"),
    (b"GACGCTGCCGACGAATAGAGAGGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]502"),
    (b"GACGCTGCCGACGAATAGCCTTGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_Index_Kit_v2_S520"),
    (b"GACGCTGCCGACGAATTAGACGGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_Index_Kit_v2_S510"),
    (b"GACGCTGCCGACGACGGAGAGAGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_Index_Kit_v2_S511"),
    (b"GACGCTGCCGACGACTAGTCGAGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_Index_Kit_v2_S513"),
    (b"GACGCTGCCGACGACTCCTTACGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]505"),
    (b"GACGCTGCCGACGACTTAATAGGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_Index_Kit_v2_S518"),
    (b"GACGCTGCCGACGAGCGATCTAGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]501"),
    (b"GACGCTGCCGACGATAAGGCTCGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_Index_Kit_v2_S521"),
    (b"GACGCTGCCGACGATACTCCTTGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]507"),
    (b"GACGCTGCCGACGATATGCAGTGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]506"),
    (b"GACGCTGCCGACGATCGCATAAGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_Index_Kit_v2_S522"),
    (b"GACGCTGCCGACGATCTACTCTGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]504"),
    (b"GACGCTGCCGACGATCTTACGCGTGTAGATCTCGGTGGTCGCCGTATCATT", "I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]517"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCAC", "Nextera_LMP_Read1_External_Adapter"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_5"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTGATATATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_25"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTGATATCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 25"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_8"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTCAACAATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_13"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTCAACTCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 13"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTTCCGTATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_14"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTTCCGTCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 14"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_1_6"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACATGTCAGAATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_15"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACATGTCAGTCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 15"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACATTCCTTTATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_27"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACATTCCTTTCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 27"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_7"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACCCACTCTTCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 23"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACCCGTCCCGATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_16"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACCCGTCCCTCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 16"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_2"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTACGTAATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_22"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTACGTTCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 22"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_12"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGAGTGGATATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_23"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_9"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_6"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGGCTACATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_11"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCACATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_18_7"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 18"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGAAACGATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_19"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGAAACTCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 19"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGGCCTTATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_20"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGGCCTTCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 20"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTTTCGGAATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_21"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTTTCGGTCTCGTATGCCGTCTTCTGCTTG", "TruSeq Adapter, Index 21"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACTAGCTTATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_10"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_4"),
    (b"GATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCTGCTTG", "TruSeq_Adapter_Index_3"),
    (b"GATCGGAAGAGCGGTTCAGCAGGAATGCCGAG", "Illumina Paired End Adapter 2"),
    (b"GATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT", "Nextera_LMP_Read2_External_Adapter"),
    (b"GATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG", "Illumina Single End Adapter 1"),
    (b"GATCGTCGGACTGTAGAACTCTGAACGTGTAGA", "Illumina Small RNA Adapter Read 2"),
    (b"GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG", "Trans2"),
    (b"GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT", "PrefixPE/2"),
    (b"TACACTCTTTCCCTACACGACGCTCTTCCGATCT", "PrefixPE/1"),
    (b"TCGGACTGTAGAACTCTGAACGTGTAGATCTCGGTGGTCGCCGTATCATT", "RNA_PCR_Primer_(RP1)_part_#_15013198"),
    (b"TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG", "Trans1"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_5_(RPI5)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACACTGATATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_25_(RPI25)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_8_(RPI8)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACAGTCAAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_13_(RPI13)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACAGTTCCATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_14_(RPI14)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_1_(RPI1)_2,9"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACATGAGCATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_26_(RPI26)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACATGTCAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_15_(RPI15)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACATTCCTATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_27_(RPI27)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCAAAAGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_28_(RPI28)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCAACTAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_29_(RPI29)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCACCGGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_30_(RPI30)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCACGATATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_31_(RPI31)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCACTCAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_32_(RPI32)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_7_(RPI7)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCAGGCGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_33_(RPI33)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCATGGCATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_34_(RPI34)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCATTTTATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_35_(RPI35)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCCAACAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_36_(RPI36)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCCGTCCATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_16_(RPI16)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_2_(RPI2)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCGGAATATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_37_(RPI37)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCGTACGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_22_(RPI22)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCTAGCTATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_38_(RPI38)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCTATACATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_39_(RPI39)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCTCAGAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_40_(RPI40)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_12_(RPI12)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGACGACATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_41_(RPI41)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGAGTGGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_23_(RPI23)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_9_(RPI9)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_6_(RPI6)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGGCTACATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_11_(RPI11)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGGTAGCATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_24_(RPI24)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTAGAGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_17_(RPI17)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_18_(RPI18)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTGAAAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_19_(RPI19)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTGGCCATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_20_(RPI20)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTTTCGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_21_(RPI21)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTAATCGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_42_(RPI42)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTACAGCATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_43_(RPI43)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTAGCTTATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_10_(RPI10)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTATAATATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_44_(RPI44)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTCATTCATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_45_(RPI45)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTCCCGAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_46_(RPI46)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTCGAAGATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_47_(RPI47)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTCGGCAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_48_(RPI48)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_4_(RPI4)"),
    (b"TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCTGCTTG", "RNA_PCR_Primer_Index_3_(RPI3)"),
    (b"TTTTTTTTTTAATGATACGGCGACCACCGAGATCTACAC", "FlowCell1"),
    (b"TTTTTTTTTTCAAGCAGAAGACGGCATACGA", "FlowCell2"),
];

/// Exact prefix match against the table, fastp's `matchKnownAdapter`: the
/// candidate must be at least as long as the entry and agree on every base of
/// it. Returns the full known sequence, which is what gets trimmed with.
pub fn match_known_adapter(seq: &[u8]) -> Option<(&'static [u8], &'static str)> {
    for &(adapter, name) in KNOWN_ADAPTERS {
        if seq.len() < adapter.len() {
            continue;
        }
        if seq[..adapter.len()] == *adapter {
            return Some((adapter, name));
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_loaded_and_ordered() {
        assert_eq!(KNOWN_ADAPTERS.len(), 234);
        let mut sorted = KNOWN_ADAPTERS.to_vec();
        sorted.sort_by(|a, b| a.0.cmp(b.0));
        assert_eq!(
            sorted.iter().map(|x| x.0).collect::<Vec<_>>(),
            KNOWN_ADAPTERS.iter().map(|x| x.0).collect::<Vec<_>>(),
            "table must be in std::map order to match fastp's tie break"
        );
    }

    #[test]
    fn finds_the_truseq_pair() {
        let (adapter, name) =
            match_known_adapter(b"AGATCGGAAGAGCACACGTCTGAACTCCAGTCAGGGGG").unwrap();
        assert_eq!(adapter, b"AGATCGGAAGAGCACACGTCTGAACTCCAGTCA");
        assert!(name.contains("TruSeq"), "got {name}");

        let (_, name2) =
            match_known_adapter(b"AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT").unwrap();
        assert!(name2.contains("TruSeq"), "got {name2}");
    }

    #[test]
    fn a_short_or_unknown_candidate_matches_nothing() {
        assert!(match_known_adapter(b"AGATCGG").is_none());
        assert!(match_known_adapter(b"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT").is_none());
    }
}
